#ORG 6000H
C1:
MVI D, 00H   // COUNTER 1 
LXI H, 7500  //Source memory pointer 

C2:  // INITIALIZE OF C2
MOV A,M    //MOVING THE CONTENT OF MEMORY TO ACCUMULTOR
INX H  // POINTING THE NEXT NUMBER
CMP M  // COMPARSION OF MEMORY WITH ACCUMULATOR
JC LOOP   // COMAPARE ACCUUMLATOR AND NEXT NUMBER
MOV B,M  // GET THE SECOND NUMBER FOR INTERCHANGE
MOV M,A   // GET THE SECOND NUMBER IN ACCUMULATOR
DCX H  // POINTING TO THE NEXT LOCATION
MOV M,B  // STORE THE SECOND NUM IN 1ST LOCATION
INX H  // POINTING THE NEXT NUM FOR NEXT COMPARISION
MVI D, 01H   // LOAD 1 IN D
LOOP:
DCR C   // DECREASE COMPARE COUNTER 
JNZ C2  // CHECK THE COMPARE COUNTER FOR ZERO 
MOV A,D  // GET FLAG BIT IN ACCUMULATOR 
RRC // TO END THE DB LOOP
JC C1
 

HLT

#ORG 7500H
#DB 35, 56, 25, 84, 69, 37, 15, 67, 82, 19
