#ORG 7000H

LDA 7501H   // 05 IN A
MOV B,A //05 IN B
LDA 7503H  //25 IN A


MVI C, 00H //QUOTIENT REGISTER C
NEXT:
CMP B  // COMPARING B WITH ACCUMULATOR
JC LOOP  // JUMP IF CARRY THAT IS A<B
INR C  // INCREMENT REGISTER C (QUOTIENT) BY 1
SUB B    //   A =a-b
JMP NEXT
LOOP:
STA 7506  // STORE REMAINDER
MOV A,C // MOVE C TO ACCUMULATOR
STA 7505 // STORE QUOTIENT

RST 1   // Terminate


#ORG 7501H
# DB 05, 00, 25
